initial begin
            rst_n         = 1'b0 ;
            new_buf_req   = 1'b0 ;
            ref_buf_numbr = 2'd0 ;

    # (HALF_CYCLE + DLY) ;

    tm_name = "001_ex2_nor_buf0_val01_ord321" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "002_ex2_nor_buf0_val01_ord312" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "003_ex2_nor_buf0_val01_ord231" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "004_ex2_nor_buf0_val01_ord213" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "005_ex2_nor_buf0_val01_ord132" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "006_ex2_nor_buf0_val01_ord123" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "007_ex2_nor_buf0_val10_ord3210" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "008_ex2_nor_buf0_val10_ord3201" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "009_ex2_nor_buf0_val10_ord3120" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "010_ex2_nor_buf0_val10_ord3102" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "011_ex2_nor_buf0_val10_ord3021" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "012_ex2_nor_buf0_val10_ord3012" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "013_ex2_nor_buf0_val10_ord2310" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "014_ex2_nor_buf0_val10_ord2301" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "015_ex2_nor_buf0_val10_ord2130" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "016_ex2_nor_buf0_val10_ord2103" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "017_ex2_nor_buf0_val10_ord2031" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "018_ex2_nor_buf0_val10_ord2013" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "019_ex2_nor_buf0_val01_ord1320" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "020_ex2_nor_buf0_val10_ord1302" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "021_ex2_nor_buf0_val10_ord1230" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "022_ex2_nor_buf0_val10_ord1203" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "023_ex2_nor_buf0_val10_ord1032" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "024_ex2_nor_buf0_val10_ord1023" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "025_ex2_nor_buf0_val10_ord0321" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "026_ex2_nor_buf0_val10_ord0312" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "027_ex2_nor_buf0_val10_ord0231" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "028_ex2_nor_buf0_val10_ord0213" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "029_ex2_nor_buf0_val10_ord0132" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "030_ex2_nor_buf0_val10_ord0123" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "031_ex2_nor_buf0_val10_ordmix01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "032_ex2_nor_buf0_val10_ordmix02" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "033_ex2_nor_buf1_ord213" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "034_ex2_nor_buf1_ord2130" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "035_ex2_nor_buf1_ordmix" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "036_ex2_nor_buf2_ord031" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "037_ex2_nor_buf2_ord0312" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "038_ex2_nor_buf2_ordmix" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "039_ex2_nor_buf3_ord120" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "040_ex2_nor_buf3_ord1203" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "041_ex2_nor_buf3_ordmix" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "042_ex2_pri_buf0123_val01" ;
    system_reset (2) ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "043_ex2_pri_buf0123_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "044_ex2_pri_buf0123_val11" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "045_ex2_pri_buf012_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "046_ex2_pri_buf012_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "047_ex2_pri_buf013_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "048_ex2_pri_buf013_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "049_ex2_pri_buf023_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "050_ex2_pri_buf023_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "051_ex2_pri_buf123_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "052_ex2_pri_buf123_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "053_ex2_pri_buf01_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "054_ex2_pri_buf01_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "055_ex2_pri_buf02_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "056_ex2_pri_buf02_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "057_ex2_pri_buf03_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "058_ex2_pri_buf03_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "059_ex2_pri_buf12_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "060_ex2_pri_buf12_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "061_ex2_pri_buf13_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "062_ex2_pri_buf13_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "063_ex2_pri_buf23_val01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "064_ex2_pri_buf23_val10" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "065_ex2_max_req_type01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "066_ex2_max_req_type02" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "067_ex2_max_req_type03" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "068_ex2_max_buf0_pri" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "069_ex2_max_buf0_buf" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "070_ex2_max_buf1_pri" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "071_ex2_max_buf1_buf" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "072_ex2_max_buf2_pri" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "073_ex2_max_buf2_buf" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "074_ex2_max_buf3_pri" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "075_ex2_max_buf3_buf" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "076_ex2_max_combo01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "077_ex2_max_combo02" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "078_ex2_max_combo03" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "079_ex2_max_reset01" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "080_ex2_max_reset02" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "081_ex2_max_reset03" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "082_ex2_max_reset04" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "083_ex2_max_reset05" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "084_ex2_max_reset06" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    check_tm ;

    tm_name = "085_ex2_max_system_ref1" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    check_tm ;

    tm_name = "086_ex2_max_system_ref2" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    check_tm ;

    tm_name = "087_ex2_max_system_ref3" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    check_tm ;

    tm_name = "088_ex2_req_buf0_cnt_value_check" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    check_tm ;

    tm_name = "089_ex2_req_buf1_cnt_value_check" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    check_tm ;

    tm_name = "090_ex2_req_buf2_cnt_value_check" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    check_tm ;

    tm_name = "091_ex2_req_buf3_cnt_value_check" ;
    system_reset (2) ;
            ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd3 ;
    # CYCLE ref_buf_numbr = 2'd2 ;
    # CYCLE new_buf_req   = 1'b1 ;
    # CYCLE new_buf_req   = 1'b0 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    # CYCLE ref_buf_numbr = 2'd1 ;
    check_tm ;

    # CYCLE $finish ;
end
